### ISSUE TITLE
How to use the toolbox

### ISSUE THREAD

**Issue by Dalasce91** [dvoulanas/automated-nctools#1]
Please provide a short description on how to use the toolbox. Should the input which is the full name of files to be accessed and the coordinates of selected area be placed in text file?

**Comment by dvoulanas** [comment]
Please find an example of how I do it, below.

clc
clear
close all;
names_xlsx_files=char("G:\temperature_paper\ECA_blend_selected_stations_only.xlsx");
for f=1:size(names_xlsx_files,1)
  [~,sheet_name]=xlsfinfo(names_xlsx_files(f,:));
  for i=1:size(sheet_name,2)
    [data.numbers{f,i}, data.txt{f,i}]=xlsread(names_xlsx_files(f,:),sheet_name{1,i});
    sheet_name_char{1,i}=char(sheet_name{1,i});
%get points
    coords_stations_dec{f,i}{:,1}=data.numbers{1}(:,2);
    coords_stations_dec{f,i}{:,2}=data.numbers{1}(:,1);
  end
end
%%inputs_for_function
ctl_pointsY=coords_stations_dec{1}{2};
ctl_pointsX=coords_stations_dec{1}{1};
ctlpoints=[ctl_pointsX,ctl_pointsY];
filename={'G:\temperature_paper\txn_mars_stat_ver2018-3_2.nc','G:\temperature_paper\txn1979-2019.nc','G:\temperature_paper\txn_ens_mean_0.1deg_reg_v19.0e.nc'};
DistClass='none';
k=[];
%starts_function
[ncdata,selpoints]=ncextract(filename,ctlpoints,DistClass,k);

**Comment by Dalasce91** [comment]
Thank you.
